version: '3'

services:
  twitter:
    build:
      context: .
      dockerfile: Dockerfile-twitter
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env

  news:
    build:
      context: .
      dockerfile: Dockerfile-news
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env

  core:
    build:
      context: .
      dockerfile: Dockerfile-core
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - 8080:8080

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
