FROM openjdk:alpine

ENV FILEPATH="target/scala-2.13/mainApplication.jar"
ENV FILE="mainApplication.jar"

WORKDIR /usr/app
ADD $FILEPATH /usr/app

EXPOSE 8080
CMD java -XX:+PrintFlagsFinal $JAVA_OPTIONS -jar $FILE
